coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
     - "Employee/src/main/java/EmployeeCommon/EmployeeScreensParameterService.java"
     - "Employee/src/main/java/EmployeeGui/"
     - "Employee/src/main/java/EmployeeDefs/"
     - "Employee/src/main/java/EmployeeDI/"
     - "Common/src/main/java/BasicCommonClasses/CartProduct.java"
     - "Common/src/main/java/BasicCommonClasses/CatalogProduct.java"
     - "Common/src/main/java/BasicCommonClasses/CustomerProfile.java"
     - "Common/src/main/java/BasicCommonClasses/ICustomerProfile.java"
     - "Common/src/main/java/BasicCommonClasses/Ingredient.java"
     - "Common/src/main/java/CommonDefs/"
     - "Common/src/main/java/BasicCommonClasses/Location.java"
     - "Common/src/main/java/BasicCommonClasses/Login.java"
     - "Common/src/main/java/BasicCommonClasses/Manufacturer.java"
     - "Common/src/main/java/BasicCommonClasses/PlaceInMarket.java"
     - "Common/src/main/java/BasicCommonClasses/ProductPackage.java"
     - "Common/src/main/java/BasicCommonClasses/SmartCode.java"
     - "Common/src/main/java/BasicCommonClasses/ForgetPassword.java"
     - "Common/src/main/java/BasicCommonClasses/GroceryList.java"
     - "Common/src/main/java/CommonDI/"
     - "Common/src/main/java/ForgetPasswordScreens/"
     - "Common/src/main/java/GuiUtils/"
     - "Common/src/main/java/SMExceptions/"
     - "Common/src/main/java/ClientServerApi/ClientServerDefs.java"
     - "Common/src/main/java/ClientServerApi/CommandWrapper.java"
     - "Common/src/main/java/ClientServerApi/ResultDescriptor.java"
     - "Common/src/main/java/ClientServerApi/CommandDescriptor.java"
     - "Common/src/main/java/UtilsContracts/"
     - "Common/src/main/java/UtilsImplementations/"
     - "Common/src/main/java/SmartcodeParser/SmartcodePrint.java"
     - "Customer/src/main/java/CustomerGuiHelpers/"
     - "Customer/src/main/java/CustomerGuiScreens/"
     - "Customer/src/main/java/CustomerDI/"
     - "Server/src/main/java/ServerRunner/"
